import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";

const title = localFont({
  src: "./fonts/Advent.ttf",
  variable: "--font-title",
  weight: "100 900",
});
const para = localFont({
  src: "./fonts/Alumni.ttf",
  variable: "--font-para",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        < Navbar />
        {children}
      </body>
    </html>
  );
}
